service: opinion-server

provider:
  name: aws
  runtime: nodejs14.x # o la versión que prefieras (puedes usar nodejs16.x o superior)
  region: us-east-1 # Asegúrate de que coincide con la región de la base de datos RDS
  environment:
    DB_HOST: opinionwebsite.cdogwouyu9yy.us-east-1.rds.amazonaws.com
    DB_USER: admin
    DB_PASSWORD: 123456789
    DB_NAME: opinionwebsite
    DB_PORT: 3306

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
